# generated by clj2nix-1.0.6
{ pkgs ? import <nixpkgs> {} }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      fetchmaven = pkgs.callPackage (pkgs.fetchurl {
        url = "https://raw.githubusercontent.com/NixOS/nixpkgs/ba5e2222458a52357a3ba5873d88779d5c223269/pkgs/build-support/fetchmavenartifact/default.nix";
        sha512 = "05m7i8hbhyfz7p2f106mfbsasjf04svd9xkgc26pl3shljrk0dfacz39wiwzm6xqw7czgrsx745vciram7al621v7634nfdq3m1x88a";
      }) {};
      makePaths = {extraClasspaths ? null}:
        (pkgs.lib.concatMap
          (dep:
            builtins.map
            (path:
              if builtins.isString path then
                path
              else if builtins.hasAttr "jar" path then
                path.jar
              else if builtins.hasAttr "outPath" path then
                path.outPath
              else
                path
                )
            dep.paths)
          packages)
        ++ (if extraClasspaths != null then [ extraClasspaths ] else []);
      makeClasspaths = {extraClasspaths ? null}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packages = [
  {
    name = "transit-java/com.cognitect";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "a97c4bb0c10cf9f024b846d528f24b04fb0c0469e06f3ba9f7b0906d490b9022aa8c6b1b00bfd4c7cf50ac3e53c9836b42ac744119af186b848c5700e45fcac6";
      version = "0.8.337";
      
    })];
  }

  {
    name = "elemental2-core/com.google.elemental2";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "elemental2-core";
      groupId = "com.google.elemental2";
      sha512 = "feac71c23abd3a3b02949d5844541490a9d6a6247b5707ca3791ef3cff93de09d712b1220e46a18b37b5bcfae5d93533fc59eaddeb7f4b8432b3a637f190f04d";
      version = "1.0.0-RC1";
      
    })];
  }

  {
    name = "data.json/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "ce526bef01bedd31b772954d921a61832ae60af06121f29080853f7932326438b33d183240a9cffbe57e00dc3744700220753948da26b8973ee21c30e84227a6";
      version = "0.2.6";
      
    })];
  }

  {
    name = "clojure/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "741b37171bda8365fe7831474b696dc9e5f4e254338d58e6d0155ea1b9af292e5b8d2ed6a8a8a6fc6983771266e47e2cb3c65e40e81fd27a6ad2ac3d37195fe3";
      version = "1.10.0";
      
    })];
  }

  {
    name = "shadow-cljsjs/thheller";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "shadow-cljsjs";
      groupId = "thheller";
      sha512 = "0e69a94b1f62a3b4fa3f49f6c453eef2ae694f77cf3a6aab9a03f94bd0e753d090c70db861ea2846ea9d4eabd70c5d21bdb7980a99f13a2e74318f09aacd1e3f";
      version = "0.0.21";
      
    })];
  }

  {
    name = "pathom/com.wsscode";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "pathom";
      groupId = "com.wsscode";
      sha512 = "63655cc113dbcda784f5ac8a6ce83d3e261f29d9190c00c0af19d075d65e620aba8984867f9955a4fdb7220ea474d7a955c9a010fbd6cdefba93f182d86cdfd0";
      version = "2.2.7";
      
    })];
  }

  {
    name = "commons-codec/commons-codec";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "d9586162b257386b5871e7e9ae255a38014a9efaeef5148de5e40a3b0200364dad8516bddd554352aa2e5337bec2cc11df88c76c4fdde96a40f3421aa60650d7";
      version = "1.11";
      
    })];
  }

  {
    name = "tools.analyzer/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "e02d7baec926e0e0a7d9c71f09fee627fbde59ae7f3cbd4abcdf0533c8a87fba8c7cf4503df34bf33777063f4b6353a022552fd003fdbea9fad5752d53609bb8";
      version = "1.0.0";
      
    })];
  }

  {
    name = "cljs-test-display/com.bhauman";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "cljs-test-display";
      groupId = "com.bhauman";
      sha512 = "d8aafc0214bb3719adbb2c957e6a7c939e0db65a0bf69c4369654f736882c3203a4eeb66670e1da18f60faa8bf97b094712472ce883a5a1a5f8dd52b8e413d96";
      version = "0.1.1";
      
    })];
  }

  {
    name = "error_prone_annotations/com.google.errorprone";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "error_prone_annotations";
      groupId = "com.google.errorprone";
      sha512 = "c9521d6b31c5dbf04b77f128ee568edfb0266c0e8d199e1050b32ff54493736d73721661f139d75da24f126c2e2dd0e851c0cf6e14e7302942be08f211f3c2b5";
      version = "2.3.1";
      
    })];
  }

  {
    name = "core.specs.alpha/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "348c0ea0911bc0dcb08655e61b97ba040649b4b46c32a62aa84d0c29c245a8af5c16d44a4fa5455d6ab076f4bb5bbbe1ad3064a7befe583f13aeb9e32a169bf4";
      version = "0.2.44";
      
    })];
  }

  {
    name = "eql/edn-query-language";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "eql";
      groupId = "edn-query-language";
      sha512 = "865e1c04409cf1579ba7940daf87b29e68273c63a60625273d29f97ee900ef331705cc053ef77f8d043934588a6644fbbf665c023e5aa7bb7e7818b3455b452f";
      version = "0.0.3";
      
    })];
  }

  {
    name = "undertow-core/io.undertow";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "undertow-core";
      groupId = "io.undertow";
      sha512 = "e4126dbe7bbb52c36f46fe0a025021255faee5a6e2756157aef69817d2eadee344272c548422a30e37b79f3b285984dfbf91026a92fd32c765d7a6adfe476e61";
      version = "2.0.25.Final";
      
    })];
  }

  {
    name = "expound/expound";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "01c3c05c115ed06c558bf0e1ff088e414b1b49450cb67e1b7d08faf2e08c1d133e511e73c7a008b1d839dd7625541594eb29b45e97c0f9544d518d9c1e88e1ea";
      version = "0.8.6";
      
    })];
  }

  {
    name = "spec.alpha/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "18c97fb2b74c0bc2ff4f6dc722a3edec539f882ee85d0addf22bbf7e6fe02605d63f40c2b8a2905868ccd6f96cfc36a65f5fb70ddac31c6ec93da228a456edbd";
      version = "0.2.176";
      
    })];
  }

  {
    name = "tools.cli/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "8f3ebc8cdd0bd68348ec5873c716dbfe11b0db26959e59eaa5a4615fe67e5c436cd9f9b701ee3e0b710d6f3924ea3d2c091835a754def584d2e0853a1fc13c0c";
      version = "0.3.7";
      
    })];
  }

  {
    name = "commons-fileupload/commons-fileupload";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a7ce44d1172b73e8d1b552fd8ff89cf0e74788193677381063ccd53fe1847f865e06bdb40ea1720e3e9791056d3fdd67b1107c7c6ab3a9fe587a52b0d6c5fc5a";
      version = "1.3.3";
      
    })];
  }

  {
    name = "animal-sniffer-annotations/org.codehaus.mojo";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "animal-sniffer-annotations";
      groupId = "org.codehaus.mojo";
      sha512 = "9e5e3ea9e06e0ac9463869fd0e08ed38f7042784995a7b50c9bfd7f692a53f0e1430b9e1367dc772d0d4eafe5fd2beabbcc60da5008bd792f9e7ec8436c0f136";
      version = "1.14";
      
    })];
  }

  {
    name = "clojure-future-spec/clojure-future-spec";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "clojure-future-spec";
      groupId = "clojure-future-spec";
      sha512 = "7e71227dd4f2a5e9c6966fa6279ed66844721ffda2c66e8cdab2bc79a976c7070763baa2104a4337433fd8d991b7aa2e8ddf981974be664dce93410c47a68bb4";
      version = "1.9.0";
      
    })];
  }

  {
    name = "tools.analyzer.jvm/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "ce9c7b51fa61c12c539f3c5c1c7fa1caf123497553d4e566c13895312faad2d2657fe6e54fe88110a6c87accb10c4c3b6ccfa87a035a7321da6c859da1d192d0";
      version = "1.1.0";
      
    })];
  }

  {
    name = "barbary-watchservice/net.incongru.watchservice";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "barbary-watchservice";
      groupId = "net.incongru.watchservice";
      sha512 = "94df2c848b711e49f08bafb407c9a12779eff7127b12a3b645917d4c4ff987782905de24bef479c4aa5543af9b4ccae92ce3cd5312799bf69ed75d7d00a39af1";
      version = "1.0";
      
    })];
  }

  {
    name = "wildfly-common/org.wildfly.common";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "wildfly-common";
      groupId = "org.wildfly.common";
      sha512 = "f056be6b88a76bf45be9acce60d4e8da0dd1fc24c8d7dc08152e3d735ad23d78a6814082d2dba5d7e00ca9f46f41af26f71133f55d0e5659213e61037e7cdfaf";
      version = "1.3.0.Final";
      
    })];
  }

  {
    name = "react-dom/cljsjs";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "react-dom";
      groupId = "cljsjs";
      sha512 = "825ee3b83a21f2ded10bb1e89d2f45bd6f9ed1beeda40080112c2275bb84d32526f39b4795db26ebb2665c07095bf8da1df25a697661587272e0b7ef10f7da10";
      version = "16.8.6-0";
      
    })];
  }

  {
    name = "json-simple/com.googlecode.json-simple";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";
      
    })];
  }

  {
    name = "transit-cljs/com.cognitect";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "318b98ddd63629f37b334bb90e625bc31ab6abcf0b1fa80d8e097551658f2d9219b5ee35869a31f2976d7d385da83bea0c07b0d097babcae241ecbd0fe8a7ecd";
      version = "0.8.256";
      
    })];
  }

  {
    name = "google-closure-library/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "4a29ae05212b508f3d4e2f5f63c542cec3fb7c0bfd0ef01718c56e0eee6798cd727b05d63af7a912bc20d7fc10e903458bce98915464e2170337151eab4ec633";
      version = "0.0-20191016-6ae1f72f";
      
    })];
  }

  {
    name = "shadow-cljs/thheller";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "shadow-cljs";
      groupId = "thheller";
      sha512 = "1598e5072f002c5860198acc313fd0bcc8d452cbfc02aece29828883f81d8812b3b87210d64bd4198b51db8d127345863193d9804806c3ad57cdb9f3f745aefd";
      version = "2.8.81";
      
    })];
  }

  {
    name = "clojurescript/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "9fe0c3628eff605a38166062ed50c22a57d62e01bc7f71fa61e1a2b8e736b0782302ba42f0d5eeb7e12f4eb562f9318c4c5874a55441570c6d1ff6f961d71f19";
      version = "1.10.597";
      
    })];
  }

  {
    name = "cljs-bean/cljs-bean";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "cljs-bean";
      groupId = "cljs-bean";
      sha512 = "044bc011a7a63929b5b12e0d8bcea1aa7f69722359e90955a91590be62441a991aa3ba4117607028dbadf02e9e7da94079609ae50e91b699f301b7461f752ffc";
      version = "1.5.0";
      
    })];
  }

  {
    name = "spec-coerce/spec-coerce";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "spec-coerce";
      groupId = "spec-coerce";
      sha512 = "76fded8a8f1d597b4dc91900b66957b4a717bf61d3c92a61bcdc107d7ad9d3384affda89a396d692a86f540e88ec5a7f37570e82ec833708e81a529d4daa6776";
      version = "1.0.0-alpha6";
      
    })];
  }

  {
    name = "commons-io/commons-io";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "4de22e2a50711f756a5542474395d8619dca0a8be0407b722605005a1167f8c306bc5eef7f0b8252f5508c817c1ceb759171e4e18d4eb9697dfdd809ac39673f";
      version = "2.6";
      
    })];
  }

  {
    name = "jsinterop-annotations/com.google.jsinterop";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jsinterop-annotations";
      groupId = "com.google.jsinterop";
      sha512 = "34330e368db2e5122350dcc9237711694e4ea03bbc315163ed5fd6fd8f649ddb2dbd1224b28207802603f869de61a15439924a1fef0e864abc134242d36e1ccb";
      version = "1.0.2";
      
    })];
  }

  {
    name = "fipp/fipp";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "b5c7c3b8f37d071a506b87885235ab47aa0ba5af0eba8193417dc31442f5fe1afc96817799c05ade2d2595c81a63c796d9bdf700e97997d312f3884eb6fd086c";
      version = "0.6.18";
      
    })];
  }

  {
    name = "jboss-logging/org.jboss.logging";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jboss-logging";
      groupId = "org.jboss.logging";
      sha512 = "2316ae680a937b5a0efe8cedc5437afc1b326682e103f7d2c3cb9a689f61402326446f08f24cebbc72dcef44ad9f81d307fcf6d6fb186e3aa3818d15ceb517f9";
      version = "3.4.0.Final";
      
    })];
  }

  {
    name = "spec-inspec/com.wsscode";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "spec-inspec";
      groupId = "com.wsscode";
      sha512 = "6ddd3a1ae290be719f8ea235d962352a7949c38fe404cf43d45e6b975635f13f53525790d77bce5543151daeadea51849499a157ea541ac0c4aa761f040c1636";
      version = "1.0.0-alpha2";
      
    })];
  }

  {
    name = "jackson-core/com.fasterxml.jackson.core";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "a1bd6c264b9ab07aad3d0f26b65757e35ff47904ab895bb7f997e3e1fd063129c177ad6f69876907b04ff8a43c6b1770a26f53a811633a29e66a5dce57194f64";
      version = "2.8.7";
      
    })];
  }

  {
    name = "asm/org.ow2.asm";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "40614e658138f2eb95bc26999545f996794c622c4d68efb9e10093743504c4b58bf22590767bc6bd93b77cdfb202c507144ba867bbc8b54d74fe7621cbc55e3a";
      version = "5.2";
      
    })];
  }

  {
    name = "react/cljsjs";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "react";
      groupId = "cljsjs";
      sha512 = "79034721f5c44fc90887f6d31adc89794132c7e21a75439cb98bb2522e87fe906041c4b92aaf9dc349dcbe9352d0f22f8d9ec78817517eebce7de99ef760265c";
      version = "16.8.6-0";
      
    })];
  }

  {
    name = "shadow-util/thheller";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "shadow-util";
      groupId = "thheller";
      sha512 = "803a068159276f5abf6d9cfa25f5c446c4c66d2eaec78393910cb2175b63a734c7c7effaf3064789608b1cf3899c287611c2d170fd78621193acc1fbbff1d5da";
      version = "0.7.0";
      
    })];
  }

  {
    name = "transit-js/com.cognitect";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "6ca0978e633e41b45ff5a76df79099ba7c4900a8ca9f6acd2a903e4ab10a1ec0c83d4127009df9dac1337debaba01f7ff1d5cced1c2159c05ef94845f73f0623";
      version = "0.8.846";
      
    })];
  }

  {
    name = "reitit-core/metosin";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "reitit-core";
      groupId = "metosin";
      sha512 = "22c57f0bb0f5c398c9156b155d78575f05980ee09fa8a5744cafc24ba149f25bbf10c5ab1aa0ca3b9a3dd83c3d23f126b3257fc5395964128d73c7915b1fa549";
      version = "0.3.10";
      
    })];
  }

  {
    name = "rhino/org.mozilla";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "rhino";
      groupId = "org.mozilla";
      sha512 = "466e7a76303ea191802b5e7adb3dff64c1d6283a25ce87447296b693b87b166f4cdd191ef7dc130a5739bfa0e4a81b08550f607c84eec167406d9be2225562dc";
      version = "1.7R5";
      
    })];
  }

  {
    name = "datascript-transit/datascript-transit";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "datascript-transit";
      groupId = "datascript-transit";
      sha512 = "dc307224c2a5c30776f0658ec8ec679d79d4daa4f9cee6b9f39c7f77ec5c39e2104e8da2a2eeee67a23aa5395b51357967dd0d825016cb7227f736b484377783";
      version = "0.3.0";
      
    })];
  }

  {
    name = "google-closure-library-third-party/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "5d1e7fdeb403f78af53023ae30fb61246bf55a4c8c097c77f5ae9784c299c927c3d3a1b63cb890e52f2f7b0eb5b01475f23e917865cfc5241d755a5d7a9f2801";
      version = "0.0-20191016-6ae1f72f";
      
    })];
  }

  {
    name = "rum/rum";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "rum";
      groupId = "rum";
      sha512 = "1b864d6bc538ea0dc521f28ee8e25f26ac0e686caa6e1b2e3a2c6a7ed48b9d26a78d288a962997fd1cdf0a01acc318125672db59cbcec911ce7609f42d2b102a";
      version = "0.12.3";
      
    })];
  }

  {
    name = "hiccup/hiccup";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "hiccup";
      groupId = "hiccup";
      sha512 = "034f15be46c35029f41869c912f82cb2929fbbb0524ea64bd98dcdb9cf09875b28c75e926fa5fff53942b0f9e543e85a73a2d03c3f2112eecae30fcef8b148f4";
      version = "1.0.5";
      
    })];
  }

  {
    name = "closure-compiler-externs/com.google.javascript";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "closure-compiler-externs";
      groupId = "com.google.javascript";
      sha512 = "84084c41c9953a880d3176830adca867d1639413fff9e8e057bae9f35d75e829feb9262bfca03c0be1d12233f71a181292c30ee4c1c561b92c5e4958f75e5c7b";
      version = "v20191027";
      
    })];
  }

  {
    name = "javassist/org.javassist";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";
      
    })];
  }

  {
    name = "xnio-nio/org.jboss.xnio";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "xnio-nio";
      groupId = "org.jboss.xnio";
      sha512 = "8bcc27fbf0d3627f914d482db98669a73caa3e841557ec2f61b03cb1be5bf69f89c89586ec2849a7160674139662f034f90b24f7c16dbb3d68db4e9e9bbcbfb2";
      version = "3.7.3.Final";
      
    })];
  }

  {
    name = "guava/com.google.guava";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "guava";
      groupId = "com.google.guava";
      sha512 = "429ceeec0350ba98e2b089b8b70ded2ec570c3a684894a7545d10592c1c7be42dacd1fad8b2cb9123aa3612575ce1b56e1bb54923443fc293f8e9adeac2762ee";
      version = "25.1-jre";
      
    })];
  }

  {
    name = "codox-klipse-theme/viebel";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "codox-klipse-theme";
      groupId = "viebel";
      sha512 = "d5d90662a10bda5a10766b41d71196e0c7053a372be3eb9b1a7d4f4306ba92a1f2e48fc46787ae800a10d0c5499778950be20a17d4d19d02669876d579857b13";
      version = "0.0.1";
      
    })];
  }

  {
    name = "msgpack/org.msgpack";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";
      
    })];
  }

  {
    name = "edamame/borkdude";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "edamame";
      groupId = "borkdude";
      sha512 = "c257ac529eec257133e265079b99cf14dbc6485174a916148c3dfe35009f31503b2403727dcb1947adc5c858cfd03962d786bdb0e877386a84f1fec37149ee91";
      version = "0.0.11-alpha.13";
      
    })];
  }

  {
    name = "jboss-threads/org.jboss.threads";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jboss-threads";
      groupId = "org.jboss.threads";
      sha512 = "0cab83da3bedc83ca912ad88297941a88aa7c1db168b1436fe18af88833e9d67c66a0c8d1273cae43bf7aa887795bb65738a1cb986645358037ec998c4d7678c";
      version = "2.3.2.Final";
      
    })];
  }

  {
    name = "j2objc-annotations/com.google.j2objc";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "j2objc-annotations";
      groupId = "com.google.j2objc";
      sha512 = "a4a0b58ffc2d9f9b516f571bcd0ac14e4d3eec15aacd6320a4a1a12045acce8c6081e8ce922c4e882221cedb2cc266399ab468487ae9a08124d65edc07ae30f0";
      version = "1.1";
      
    })];
  }

  {
    name = "transit-clj/com.cognitect";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "d13f18d898195d69209675877ff197472e051dd6b9ba7b127f4d5b0e2f24b7c60cdddddd7a4a86f1fc78717ddc5c95bc88c24044dcb571a1c234d1250f38e67c";
      version = "0.8.313";
      
    })];
  }

  {
    name = "quoin/quoin";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "quoin";
      groupId = "quoin";
      sha512 = "792e2861abd79747fde6cbd107424b2b471449cb555106070e2d073787e79ddbda66504b0a79caa713f21051d0826e6edb9deea68d811d983ab95289b150d612";
      version = "0.1.2";
      
    })];
  }

  {
    name = "args4j/args4j";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "args4j";
      groupId = "args4j";
      sha512 = "5f0651234c8f8b130fddb39fa832c6da47d3e21bc3434307554314c47e672c28d005c64e9effe85d552190cfc27966b1f005740ffd40b4e1bec2cb257d7feedb";
      version = "2.0.26";
      
    })];
  }

  {
    name = "crypto-random/crypto-random";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "0551fba1c86871b1e70fe80679d78f11bec678ccad07f7b40cc7de1e97a3ec11f7df43dd86508869765cb1a6b2b5aa5cac6d10a5d319a26df8f513ec2bfa29e8";
      version = "1.2.0";
      
    })];
  }

  {
    name = "base/com.google.jsinterop";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "base";
      groupId = "com.google.jsinterop";
      sha512 = "7a52fd9332d122b48b4c2c7dd6db5781120ee3e5cd4f8e71381fc70522d6ecb56dfcf01dfe32df21d5d7b6e7cc7dee199d0b20b5b326656c43f90acbf570155f";
      version = "1.0.0";
      
    })];
  }

  {
    name = "ring-codec/ring";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "696a9ec9b66f6d28ed96b1d8dd1881c430a4465b0d351b0bf3864924026b56469ccd342357c41ab9db59eb1b09b345bd75173c1e543b10cd611f17a72e3fc1b8";
      version = "1.1.1";
      
    })];
  }

  {
    name = "shadow-client/thheller";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "shadow-client";
      groupId = "thheller";
      sha512 = "fef20d72aab589ce40c5e5d43ac8e58068483b50603dc6e3fb509c783f8e17efba3e459538a989d1e4ef88847af1d2013516788b58d58bb6ea71132fb5165799";
      version = "1.3.2";
      
    })];
  }

  {
    name = "core.rrb-vector/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "4e410c4a90a869e98d5d69a8a6dd6427e9d77b70e1a2b54cf24baf23389f22e7a208375783c2fdc5c1a5acfb8511a5c5ed57ad1a946d5bffd203f453d90a6155";
      version = "0.0.14";
      
    })];
  }

  {
    name = "cljs-drag-n-drop/cljs-drag-n-drop";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "cljs-drag-n-drop";
      groupId = "cljs-drag-n-drop";
      sha512 = "05521a2f94d18409f57cdcd3da71ea97304ef112c148a1c012d1fed78978f3871d6c5c3bc8a1ba2b57a8b999ad863b34b6031b595c1e4d0893a326d18d392742";
      version = "0.1.0";
      
    })];
  }

  {
    name = "crypto-equality/crypto-equality";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
      
    })];
  }

  {
    name = "promesa/funcool";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "promesa";
      groupId = "funcool";
      sha512 = "488d4503a0c8dca1071659172bb18f98d374cfbbe6a0d63934462f355338285d9b6c7136d1b84b239a2ca878c120625cf3b59e0cf00c44cc722bcd4d24f12e2e";
      version = "4.0.2";
      
    })];
  }

  {
    name = "checker-qual/org.checkerframework";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "checker-qual";
      groupId = "org.checkerframework";
      sha512 = "3c38b0b9e0bde464268cff5fdb1894a048240b039093ee3abe5b32976a22737d26b355f8793f630a7f0b319fdb019a6fcd9ee1d5219676f0f10c0b0f496b61b7";
      version = "2.0.0";
      
    })];
  }

  {
    name = "wildfly-client-config/org.wildfly.client";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "wildfly-client-config";
      groupId = "org.wildfly.client";
      sha512 = "81b6d7aaaf7d81701fd6c2feb8fc2f2af23ef67f057d09d4b8c1a33efc544f7af90035e000aeace95b7ceaf34219493d088e190f883656ef0a225ec5742a4349";
      version = "1.0.0.Final";
      
    })];
  }

  {
    name = "hickory/hickory";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "hickory";
      groupId = "hickory";
      sha512 = "50a84debfbccf3fbc99a49abd5b25b155fe1bb45349b821d893da6fbd3ccae5d6d7665c5602a940318eea6e38a3d870a866447cd9d3f96b5c35e3596adc07461";
      version = "0.7.1";
      
    })];
  }

  {
    name = "persistent-sorted-set/persistent-sorted-set";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "persistent-sorted-set";
      groupId = "persistent-sorted-set";
      sha512 = "69c02b9968d415f45820a41e04aefba78680f36a742ee7077e6f159dfee6d759fdc0dfaadb115b10e88ba2f103d9b0db7637d01a351b1f8fe75f7cefecac5bb1";
      version = "0.1.2";
      
    })];
  }

  {
    name = "glogi/lambdaisland";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "glogi";
      groupId = "lambdaisland";
      sha512 = "61dffc304cd412bd36f70bf9bea9485157209bbf7a836b84c83d00ea2b7592963dcfcb4ea46262c7d29e4e7246c618c74fc4e7cc1c11383e366f34cf284dceea";
      version = "1.0.74";
      
    })];
  }

  {
    name = "jna/net.java.dev.jna";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jna";
      groupId = "net.java.dev.jna";
      sha512 = "a380b303d5ece14b3a45dbac8d06e3f39fe5e09f3a5d08c161262c47a14326a9f5cbcdc56d6fabf6efcdb7449c4a2e43e696ec6c8c35730fb34a2993c6647948";
      version = "3.2.2";
      
    })];
  }

  {
    name = "cljs-time/com.andrewmcveigh";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "cljs-time";
      groupId = "com.andrewmcveigh";
      sha512 = "804a57fe3c912aca3fdaac9f25fabf6cc453d3884e3be96f1a522332d6351ab4643494c1c6992306c7a912e2ebddbe5aee684262aee7b63c5cefd11778223d25";
      version = "0.5.2";
      
    })];
  }

  {
    name = "core.match/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "core.match";
      groupId = "org.clojure";
      sha512 = "52ada3bbe73ed1b429be811d3990df0cdb3e9d50f2a6c92b70d490a8ea922d4794da93c3b7487653f801954fc599704599b318b4d7926a9594583df37c55e926";
      version = "1.0.0";
      
    })];
  }

  {
    name = "tools.reader/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "290a2d98b2eec08a8affc2952006f43c0459c7e5467dc454f5fb5670ea7934fa974e6be19f7e7c91dadcfed62082d0fbcc7788455b7446a2c9c5af02f7fc52b6";
      version = "1.3.2";
      
    })];
  }

  {
    name = "jsoup/org.jsoup";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jsoup";
      groupId = "org.jsoup";
      sha512 = "1d169f1c509ba7c78f92240ea977f2f8d34b340860ebe2377fcce87e551ca54e5fb750491f7b32488e6db2652bbf96010decec4632a24e64f930a681cdb248a1";
      version = "1.9.2";
      
    })];
  }

  ({
    name = "datascript/datascript";
    paths =
      let gitSrc = pkgs.fetchgit {
            name = "datascript";
            url = "https://github.com/tiensonqin/datascript";
            rev = "7c2822565d9a114c7d8604c335af89de4640e2e5";
            sha256 = "15znkx4q9s1k8z5mhsgrixg8p337iljggy5vd8ywy54hdl8pmc88";
          };
      in map (path: gitSrc + path) [
        "/src"
      ];
  })

  {
    name = "tongue/tongue";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "tongue";
      groupId = "tongue";
      sha512 = "24cefb5e6b5f68442ce761f1bb5fc7d498f9fe39cb0502eef5cbe0d4e629ab8841ed1b007e0db4ed2bb538d35b4018909c280886a9466f8b2a57ff820048b4d2";
      version = "0.2.9";
      
    })];
  }

  {
    name = "nrepl/nrepl";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "f9ffc647820e772428781cb4ccd4f84a7d903afffe64418af55c95bd7bc21e1722591ac425d1be366d8f4f4596debf0c1b006957848473d3c515f4187cd5cb86";
      version = "0.6.0";
      
    })];
  }

  {
    name = "re2j/com.google.re2j";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "re2j";
      groupId = "com.google.re2j";
      sha512 = "a9bd66b95ede4d7576358b974db8059eef884d0ce59a1e065a3be1e84b97f50af7bbc6429968750f82faab1e666bbb9e51f8685e12051bb5407b3943804f04f6";
      version = "1.3";
      
    })];
  }

  {
    name = "xnio-api/org.jboss.xnio";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "xnio-api";
      groupId = "org.jboss.xnio";
      sha512 = "0540ad5d012a872a3e56aab3fa87f486cb429eafc91f1584e6797148aef74a5caff19524f38a2933f4f643eec8afd4d5aeee8ac2bf801f973024f268ee2adcf4";
      version = "3.7.3.Final";
      
    })];
  }

  {
    name = "dommy/prismatic";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "dommy";
      groupId = "prismatic";
      sha512 = "753da7afbf48c1d203b09a71b865995879bfabf1473fe7b42ee0ce62673e75412265679962ca464b752b922104bcd30e08f8952f690f143bbd500d8697de0f51";
      version = "1.1.0";
      
    })];
  }

  {
    name = "closure-compiler-unshaded/com.google.javascript";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "5b7f4ead38dd96137b4f851d248c451c8f21607b7b5c4012170abbe2cb4dc995c99ecbfd92815b4fde3fbab98ab2b8438b1c11d53221e008b0e40799246d35f1";
      version = "v20191027";
      
    })];
  }

  {
    name = "test.check/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "bf57571a9d31d50cf15b38134f4d7c34d03eb458bc62b30c7a1dbf233e300c67f1fda6673dbd1584a0497cf8875f972e6697e7f13d0c3e70e4254697b1b75cc6";
      version = "0.10.0-alpha3";
      
    })];
  }

  {
    name = "reitit-frontend/metosin";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "reitit-frontend";
      groupId = "metosin";
      sha512 = "5a3dae8315e2c138fd52e76717963870660a096d2b4e5c35336331e6bbd3d9766c17227139e39938836f6253a56c08d37219be71b7ed495f2a47fd0ff3930c17";
      version = "0.3.10";
      
    })];
  }

  {
    name = "protobuf-java/com.google.protobuf";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "protobuf-java";
      groupId = "com.google.protobuf";
      sha512 = "230fc4360b8b2ee10eb73d756c58478b6c779433aa4ca91938404bbfd0ada516d3215664dbe953c96649e33bbef293958e4ad4616671f0c246883196ece92998";
      version = "3.0.2";
      
    })];
  }

  {
    name = "core.memoize/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "37308fcbbe64d0a2802917ef5a589075f81086d63e08c71a9a1b648b73dd362e5bdc8f756084fde1f4b1964ba82a6dc06b2119460281b7949a271d82e6a47a7e";
      version = "1.0.236";
      
    })];
  }

  {
    name = "hawk/hawk";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "hawk";
      groupId = "hawk";
      sha512 = "617ef041b7ef98c96395fd997a0f5f5028db267c4eac367c47a306405ea1eb825f826e42be8aa4462f753d264c52496e39854e4061e9ee40712dde2f57aa9efe";
      version = "0.2.11";
      
    })];
  }

  {
    name = "data.priority-map/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "fb2d703468fb6d5f28c38f25e8e7acdaf02d2fa1ac23c14a9ff065873e88c9b74e155e73e5069436d674d7ef8547f01bc9777b7ae3b9dcde67cbd327d4a20c06";
      version = "1.0.0";
      
    })];
  }

  {
    name = "piggieback/cider";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "piggieback";
      groupId = "cider";
      sha512 = "fd19cc918e0fb4bcd7c667ccc16ef6a9fb9dceb3e8e5bd944c67c5c53fb9d0147710983a6ceccc12c0d03f85df0eaa33cccc96412bd5016b010a845e17446c33";
      version = "0.4.1";
      
    })];
  }

  {
    name = "sci.impl.reflector/borkdude";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "sci.impl.reflector";
      groupId = "borkdude";
      sha512 = "c747fd347e6aba9578d105298b7c7402f53e8639d5c8e6dc83b127f3c413feeb1b9dead7405ac2c4345f02290902e8a2affbec749474481e9c9f19b3d049f18f";
      version = "0.0.1";
      
    })];
  }

  {
    name = "sci/borkdude";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "sci";
      groupId = "borkdude";
      sha512 = "37da8d9cf3e22d736be7c20591a84ea8d679b69fe6897b359407a3073c5da3ac67b465e66a88f0f6e3c0e7183ae727cb6a5de6fc3d61acf2e6db5845f5aebfaf";
      version = "0.1.1-alpha.6";
      
    })];
  }

  {
    name = "jsr305/com.google.code.findbugs";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jsr305";
      groupId = "com.google.code.findbugs";
      sha512 = "bb09db62919a50fa5b55906013be6ca4fc7acb2e87455fac5eaf9ede2e41ce8bbafc0e5a385a561264ea4cd71bbbd3ef5a45e02d63277a201d06a0ae1636f804";
      version = "3.0.2";
      
    })];
  }

  {
    name = "ring-core/ring";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "14be43af9e9938b07f0cc22be431720043445a3f46ce9c72e67d81d724f54e2311436a732ba3c2bb0c8abafc2ef077c1778773f02f018cb537820dc89b8b5213";
      version = "1.7.1";
      
    })];
  }

  {
    name = "core.cache/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "6e4e126f23b20120c50a4dbefbe1b3b9bd98f0a7b8fa83affa267ff7f0de09542d2727243859a1ea346bda5b782d4ae0110f6c2b169c298261707a1fdadaedb0";
      version = "1.0.207";
      
    })];
  }

  {
    name = "meta-merge/meta-merge";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "meta-merge";
      groupId = "meta-merge";
      sha512 = "079339d69a18e88a7cf5ce37e29bf7d9b25c93011866fac3012b11444f9e3d69f4dc017a3e88ad20faa790b38e343e0b71e9e11c44028434da3f368f377e4458";
      version = "1.0.0";
      
    })];
  }

  {
    name = "medley/medley";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "medley";
      groupId = "medley";
      sha512 = "40d9e4f570573e45ff99634d6446f0cd7f26443db0a616abbf5ea55ee731ca9d3245d212eb02070327ce4b208667699bcfcf81ad4ad6565bdc40f1b2970d5ed7";
      version = "1.2.0";
      
    })];
  }

  {
    name = "hiccups/hiccups";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "hiccups";
      groupId = "hiccups";
      sha512 = "aea52df313d89fa846f8ebe5881c11329c17e096047fbbc9367d161092b64435f464e344b4f3cf88ce703c37aebf3aed9e817c82bb29a2b49fc83711d39f84bd";
      version = "0.3.0";
      
    })];
  }

  {
    name = "core.async/org.clojure";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "3a656c6f775940013a6b2e993bb60085246933c559d3c686fc7c2f5f82c70b672921d4bee964de2c31f6bf876cf3bc266ee39e918b6c310f5fd6254f65cb2064";
      version = "1.3.610";
      
    })];
  }

  {
    name = "jaxb-api/javax.xml.bind";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "0c5bfc2c9f655bf5e6d596e0c196dcb9344d6dc78bf774207c8f8b6be59f69addf2b3121e81491983eff648dfbd55002b9878132de190825dad3ef3a1265b367";
      version = "2.3.0";
      
    })];
  }

  {
    name = "gson/com.google.code.gson";
    paths = [(fetchmaven {
      inherit repos;
      artifactId = "gson";
      groupId = "com.google.code.gson";
      sha512 = "c3cdaf66a99e6336abc80ff23374f6b62ac95ab2ae874c9075805e91d849b18e3f620cc202b4978fc92b73d98de96089c8714b1dd096b2ae1958cfa085715f7a";
      version = "2.7";
      
    })];
  }

  ];
  }
  